### PR TITLE
Upgrade to latest upstream release 0.7.22

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
still need to fix the sha256…

**Comment by isuruf** [comment]
Can you add this patch, https://github.com/conda-forge/pynac-feedstock/commit/a53b1514cb35c52a14aedd0f17a2e91466933316?

**Comment by saraedum** [comment]
Oops, I thought it would create a branch in my namespace.

**Comment by isuruf** [comment]
Can you send a PR from your fork? I cancelled all the jobs for now

**Comment by saraedum** [comment]
Sure. Should we also delete the 0.7.16 branch?

**Comment by isuruf** [comment]
> Should we also delete the 0.7.16 branch?

I kept it so that I can have the same version as sage 8.2 and then updated with the patch. No harm in keeping it.

**Pull request closed without merging**
